name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v3

      - name: Ustawienie środowiska Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalacja zależności
        run: pip install -r requirements.txt

      - name: Uruchomienie testów
        run: pytest --cov=routes tests/

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v3

      - name: Budowanie obrazu Docker
        run: docker build -t ai-backend .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v3

      - name: Wdrożenie na serwer
        run: |
          ssh user@adres-serwera "docker pull twoj-obraz-docker && docker-compose up -d"
